### ISSUE TITLE
Where to find the RJ45 Teensy enclosure displayed in the README.md file? 

### ISSUE THREAD

**Issue by barravi** [jpagliaccio/Terminal-J#1]
Hello

sorry I didn't know how else to contact you. I would be very interested in that compact enclosure for the teensy board with the RJ45 plug included, it doesn't seem to be 3D printed but I cannot find it for sale anywhere. 

Could you help me out please? Thanks in advance! 

/V

**Comment by jpagliaccio** [comment]
Hey - Thanks for reaching out.

We used a Ethernet Jack - it's a GIGAMAX by Leviton CAT5e 568

Like this:
https://www.amazon.com/Leviton-5G108-RY5-GigaMax-QuickPort-Connector/dp/B000U3BTSE/ref=asc_df_B000U3BTSE/?tag=hyprod-20&linkCode=df0&hvadid=167151358503&hvpos=&hvnetw=g&hvrand=3294878374519412740&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1023239&hvtargid=pla-314819632925&psc=1

The case is this one from UNICOM:

https://www.ebay.com/i/163217849737?chn=ps&norover=1&mkevt=1&mkrid=711-117182-37290-0&mkcid=2&itemid=163217849737&targetid=1068323860990&device=c&mktype=pla&googleloc=1023239&poi=&campaignid=10459841973&mkgroupid=104612009900&rlsatarget=pla-1068323860990&abcId=2146002&merchantid=112136006&gclid=Cj0KCQiAmfmABhCHARIsACwPRAAAVuzWSflwbap8u4xMxoFbdG-uHZC8TPNNDKOv4UzsEBJCKsrSLhQaAkrDEALw_wcB

There are others like it but that size just fits the teensy - very snug.

Good Luck.

JP
